New feature: network policies
MaikuMori/helm-charts pull request #49
Opened 2024-10-24 14:16 UTC by anthosz

_Descriptive description goes here._

Tasks:

 - [ ] I've made changes
 - [ ] I've bumped chart's version in `Chart.yaml`
 - [ ] I've added changes to charts `CHANGELOG.md`
 - [ ] I've run [`helm-docs`](https://github.com/norwoodj/helm-docs)

2024-10-25 01:34 UTC, MaikuMori commented
It's currently failing test:

> Error: UPGRADE FAILED: template: gotenberg/templates/networkpolicy.yaml:1:14: executing "gotenberg/templates/networkpolicy.yaml" at <.Values.networkPolicy.enabled>: nil pointer evaluating interface {}.enabled

This happens because of how helm upgrades charts. To fix it you need to check if `networkPolicy` exists before checking if enabled in truthy.

This issue only happens on upgrades, not fresh installs.

2024-10-25 06:30 UTC, anthosz commented
> It's currently failing test:
> 
> > Error: UPGRADE FAILED: template: gotenberg/templates/networkpolicy.yaml:1:14: executing "gotenberg/templates/networkpolicy.yaml" at <.Values.networkPolicy.enabled>: nil pointer evaluating interface {}.enabled
> 
> This happens because of how helm upgrades charts. To fix it you need to check if `networkPolicy` exists before checking if enabled in truthy.
> 
> This issue only happens on upgrades, not fresh installs.

Patch pushed + aligned with master

2024-10-26 03:27 UTC, MaikuMori requested changes
I'm going to add a couple changes too so it's bundled in the same release.

2024-10-26 03:27 UTC, MaikuMori commented on charts/gotenberg/templates/networkpolicy.yaml
> +  name: {{ include "varnish-cache.fullname" . }}
Copy-paste?

2024-10-26 03:27 UTC, MaikuMori commented on charts/gotenberg/templates/networkpolicy.yaml
> +    {{- include "varnish-cache.labels" . | nindent 4 }}
Same here.

2024-10-26 03:27 UTC, MaikuMori commented on charts/gotenberg/templates/networkpolicy.yaml
> +{{- if .Values.networkPolicy.allowIngress }}
This seems a bit weird way to structure it, but I think it's ok for now. We can always accept a PR to change it.

2024-10-26 04:49 UTC, merged

2024-10-26 06:27 UTC, anthosz commented on charts/gotenberg/templates/networkpolicy.yaml
> +{{- if .Values.networkPolicy.allowIngress }}
Indeed, I copy paste from my PR for varnish, https://github.com/varnish/helm-varnish-cache/pull/24

It's not really clean but it allow to unblock when we use strict mode on cni :)

TODO: add a default schema that took into account the port & probably a matchexpressions based on ns or pod selector

Thank you!